[[AndExport]]
git-tree-sha1 = "e749825f8dd3dd3ac9f089cc48ef0f41de488086"
repo-rev = "master"
repo-url = "https://github.com/pengwyn/AndExport.jl"
uuid = "4484d908-372d-4f90-b90b-0ec97f005b8c"
version = "0.1.1"

[[AutoParameters]]
git-tree-sha1 = "9fcbe5d7ab6bf744e2f8a992e102d891fe749ef5"
repo-rev = "master"
repo-url = "https://github.com/pengwyn/AutoParameters.jl"
uuid = "2688778c-3549-4980-b6fe-7a9ff5c92ab2"
version = "0.1.3-dev"

[[DiffEqBase]]
git-tree-sha1 = "a9c8e0f07456d5198925bf5dad118b1be3bd4021"
repo-rev = "callback-zero"
repo-url = "https://github.com/pengwyn/DiffEqBase.jl"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
version = "6.47.0"

[[ObjectSaving]]
git-tree-sha1 = "493ca13f69417f9eb848b12225326af52dbebd23"
repo-rev = "master"
repo-url = "https://github.com/pengwyn/ObjectSaving.jl"
uuid = "48b21832-91ca-4963-a617-80b23448076a"
version = "0.1.1-dev"
